name: build windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure
        run: cmake --preset dev -DCMAKE_CXX_COMPILER=cl

      - name: Build
        run: cmake --build --preset dev

      - name: Test
        run: ctest --preset dev -L unit --parallel
